sudo: required
services:
        - docker 

before_install:
        - docker build -t claudi2909/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true claudi2909/docker-react npm run test 

